src/comidApp.MVC/Models/ErrorViewModel.cs
namespace comidApp.MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    //(servicios) crear restaurante / cliente
}

src/comidApp.MVC/ViewModels/PlatoViewModel.cs
using comidApp.Core;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace comidApp.MVC.ViewModels
{
    public class PlatoViewModel
    {
        public string Nombre { get; set; } = string.Empty;
        public string Descripcion { get; set; } = string.Empty;
        public ushort idPlato { get; set; }
        public double PrecioUnitario { get; set; }
        public ushort IdRestaurante { get; set; }
        public ushort Disponibilidad { get; set; }
        public SelectList? Restaurantes { get; set; }

        public PlatoViewModel(IEnumerable<Restaurante> restaurantes)
        {
            Restaurantes = new (restaurantes, 
                                dataTextField: nameof(Restaurante.Nombre),
                                dataValueField: nameof(Restaurante.idRestaurante));
        }
        public PlatoViewModel()
        {
            
        }
        public Plato Instancia
            => new Plato (Nombre, Descripcion, idPlato, PrecioUnitario, IdRestaurante, Disponibilidad);
    }
}

src/comidApp.MVC/Controllers/ClienteController.cs
using comidApp.Core;
using Microsoft.AspNetCore.Mvc;

namespace comidApp.MVC.Controllers;

public class ClienteController : Controller
{
    private readonly Servicio _servicio;
    public ClienteController(Servicio servicio) => _servicio = servicio;

    [HttpGet]
    public IActionResult AltaCliente() => View();

    [HttpPost]
    public IActionResult AltaCliente(Cliente cliente)
    {
        try
        {
            _servicio.AltaCliente(cliente);
            return RedirectToAction(nameof(AltaCliente));
        }
        catch (System.Exception)
        {
            return NotFound();
            throw;
        }
    }

}

src/comidApp.MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using comidApp.MVC.Models;

namespace comidApp.MVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/comidApp.MVC/Controllers/PlatoController.cs
using comidApp.Core;
using comidApp.MVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace comidApp.MVC.Controllers;
public class PlatoController : Controller
{
    private readonly Servicio _servicio;
    public PlatoController(Servicio servicio) => _servicio = servicio;

    public IActionResult Listado()
    {
        var platos = _servicio.ObtenerPlatos();
        return View(platos);
    }

    [HttpGet]
    public IActionResult AltaPlato()
    {
        var vmPlato = new PlatoViewModel(_servicio.ObtenerRestaurantes());
        return View(vmPlato);
    }

    [HttpPost]
    public async Task<IActionResult> AltaPlato(PlatoViewModel platoVM)
    {
        if (!ModelState.IsValid)
            return View("AltaPlato", platoVM);

        var plato = platoVM.Instancia;
        
        try
        {

            _servicio.AltaPlato(plato);
        }

        catch (System.Exception)
        {
            throw;
        }
        return RedirectToAction(nameof(Detalle), new { id = plato.idPlato });
    }
    public IActionResult Detalle(short id)
    {
        var plato = _servicio.ObtenerPlatos().FirstOrDefault(p => p.idPlato == id);

        if (plato is null)
        
            return NotFound();

        return View(plato);
    }

}

src/comidApp.MVC/Controllers/RestauranteController.cs
using comidApp.Core;
using Microsoft.AspNetCore.Mvc;

namespace comidApp.MVC.Controllers;
public class RestauranteController : Controller
{
    private readonly Servicio _servicio;
    public RestauranteController(Servicio servicio) => _servicio = servicio;

    [HttpGet]
    public IActionResult Alta() => View();

    [HttpPost]
    public IActionResult Alta(Restaurante restaurante)
    {
        try
        {
            _servicio.AltaRestaurante(restaurante);
            return RedirectToAction(nameof(Alta));
        }
        catch (System.Exception)
        {
            return NotFound();
            throw;
        }
        
    }
}

src/comidApp.MVC/Views/Cliente/AltaCliente.cshtml
@using comidApp.Core;
@model Cliente;
@{
    ViewData["Title"] = "Cliente - AltaCliente";
}

<form asp-controller="Cliente" asp-action="AltaCliente" method="post">
    <div asp-validation-summary="All"></div>
    <div><input type="hidden" asp-for="@Model.IdCliente" /></div>
    <div class="row g-3 align-items-center">
        <div class="col-auto">
            <label asp-for="Nombre" class="col-form-label">Nombre</label>
        </div>
        <div class="col-auto">
            <input asp-for="Nombre" class="form-control" />
        </div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="col-auto">
            <label asp-for="Apellido" class="col-form-label">Apellido</label>
        </div>
        <div class="col-auto">
            <input asp-for="Apellido" class="form-control" />
        </div>
        </div>
        <div class="row g-3 align-items-center">
            <div class="col-auto">
                <label asp-for="Email" class="col-form-label">Email</label>
            </div>
            <div class="col-auto">
                <input asp-for="Email" class="form-control" />
            </div>
            <div class="row g-3 align-items-center">
                <div class="col-auto">
                    <label asp-for="Clave" class="col-form-label">Clave</label>
                </div>
                <div class="col-auto">
                    <input asp-for="Clave" class="form-control" type="password"/>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary"><i class="bi bi-dribbble">Agregar cliente</i></button>
    </div>
</form>

src/comidApp.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "ComidApp";
}

<div class="text-center">
    <h1 class="display-4">Bienvenidos</h1>
    <p>Bienvenidos a nuestra seleccion mas sofisticada de restaurantes</a>.</p>
</div>

<html>
<body>
<center>
<img src="https://i.pinimg.com/736x/a4/aa/f6/a4aaf62f3f9c18ffe5bba89a713b324b.jpg" width="500" height="380">
</center>
</body>
</html>

src/comidApp.MVC/Views/Plato/AltaPlato.cshtml
@using comidApp.MVC.ViewModels;
@model PlatoViewModel;
@{
    ViewData["Title"] = "Plato - AltaPlato";
}

<form asp-controller="Plato" asp-action="AltaPlato" method="post">
    <div asp-validation-summary="All"></div>
    <div><input type="hidden" asp-for="@Model.idPlato" /></div>
    <div class="row g-3 align-items-center">
        <div class="col-auto">
            <label asp-for="Nombre" class="col-form-label">Nombre</label>
        </div>
        <div class="col-auto">
            <input asp-for="Nombre" class="form-control" />
        </div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="col-auto">
            <label asp-for="Descripcion" class="col-form-label">Descripcion</label>
        </div>
        <div class="col-auto">
            <input asp-for="Descripcion" class="form-control" />
        </div>
        <div class="row g-3 align-items-center">
            <div class="col-auto">
                <label asp-for="PrecioUnitario" class="col-form-label">PrecioUnitario</label>
            </div>
            <div class="col-auto">
                <input asp-for="PrecioUnitario" class="form-control" />
            </div>
            <div class="row g-3 align-items-center">
                <div class="col-auto">
                    <label asp-for="Disponibilidad" class="col-form-label">Disponibilidad</label>
                </div>
                <div class="col-auto">
                    <input asp-for="Disponibilidad" class="form-control" />
                </div>
            </div>
        </div>
    </div>
    <div class="row g-2 align-items-center">
        <div class="col-auto">
            <select asp-items="Model.Restaurantes" asp-for="IdRestaurante" class="form-select">
                @if (Model.idPlato == 0)
                {
                    <option selected="selected" value="" disabled>Seleccione un restaurante</option>
                }
            </select>
        </div>
        <button type="submit" class="btn btn-primary"><i class="bi bi-dribbble">Agregar plato</i></button>
</form>

src/comidApp.MVC/Views/Plato/Detalle.cshtml
@using comidApp.Core;
@model Plato;
@{
    ViewData["Title"] = "Plato - AltaPlato";
}

<h1>@Model.Nombre</h1>

<label>Descripcion: </label> @Model.Descripcion<br>

<label>Disponibilidad: </label> @Model.Disponibilidad<br>

<label>Precio: </label> $@Model.PrecioUnitario<br>

<a asp-action="Listado">Listado Platos</a>

src/comidApp.MVC/Views/Plato/Listado.cshtml
@using comidApp.Core;
@model IEnumerable<Plato>;
@{
    ViewData["Title"] = "Plato - AltaPlato";
}

@if (Model.Count() != 0)
{
    <h3>Platos</h3>
    <br><br>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Nombre: </th>
                <th scope="col">Precio: </th>
            </tr>
        </thead>
        <tbody class="" >
            @foreach (var plato in Model)
            {
                <tr>
                    <th scope="row"><a asp-action="Detalle" asp-route-Id="@plato.idPlato"> @plato.Nombre</a></th>
                    <th scope="row"><a asp-action="Detalle" asp-route-Id="@plato.idPlato"> @plato.PrecioUnitario</a></th>
                    @* <td><a asp-action="Detalle" asp-route-Id="@plato.idPlato">Detalle <i class="bi bi-eyeglasses" style="color: black;"></i></a></td> *@
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No hay platos cargados.</p>
}

src/comidApp.MVC/Views/Restaurante/Alta.cshtml
@using comidApp.Core;
@model Restaurante;
@{
    ViewData["Title"] = "Restaurante - Alta";
}

<form asp-controller="Restaurante" asp-action="Alta" method="post">
    <div asp-validation-summary="All"></div>
    <div><input type="hidden" asp-for="@Model.idRestaurante" /></div>
    <div class="row g-3 align-items-center">
        <div class="col-auto">
            <label asp-for="Email" class="col-form-label">Email</label>
        </div>
        <div class="col-auto">
            <input asp-for="Email" class="form-control" />
        </div>
        <div class="row g-3 align-items-center">
            <div class="col-auto">
                <label asp-for="Nombre" class="col-form-label">Nombre</label>
            </div>
            <div class="col-auto">
                <input asp-for="Nombre" class="form-control" />
            </div>
            <div class="row g-3 align-items-center">
                <div class="col-auto">
                    <label asp-for="Domicilio" class="col-form-label">Domicilio</label>
                </div>
                <div class="col-auto">
                    <input asp-for="Domicilio" class="form-control" />
                </div>
                <div class="row g-3 align-items-center">
                    <div class="col-auto">
                        <label asp-for="Clave" class="col-form-label">Clave</label>
                    </div>
                    <div class="col-auto">
                        <input asp-for="Clave" class="form-control" type="password"/>
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary"><i class="bi bi-dribbble">Agregar restaurante</i></button>
    </div>
</form>

@* <a asp-controller="Restaurante" asp-action="Alta" asp-route>
<button type="submit" class=""><i class =""> *@

src/comidApp.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - comidApp.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/comidApp.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">comidApp.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Restaurante
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-controller="Restaurante" asp-action="Alta">Alta</a></li>
                        </ul>
                    </li>
                </div>
                <div>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Plato
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-controller="Plato" asp-action="AltaPlato">Alta</a></li>
                            <li><a class="dropdown-item" asp-controller="Plato" asp-action="Listado">Listado</a></li>
                        </ul>
                    
                    </li>
                </div>
                <div>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Cliente
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-controller="Cliente" asp-action="AltaCliente">Alta</a></li>
                        </ul>
                    </li>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - comidApp.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>